openapi: 3.1.0
info:
  title: Mosey Accounts Signup API
  description: If you'd like to use the Mosey API, please contact sales@mosey.com.
  version: 1.0.0
  x-logo:
    url: null
tags:
- name: Signup
paths:
  /v2/signup/sessions:
    post:
      summary: Create Hosted Signup Session
      operationId: Create_Hosted_Signup_Session_v2_signup_sessions_post
      parameters:
      - name: authorization
        in: header
        required: false
        schema:
          type: string
          title: Authorization
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/app__platform__public__HostedSignupRequest'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/app__platform__public__HostedSignupResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      tags:
      - Signup
  /v2/signup:
    post:
      summary: Signup To Create A Legal Entity
      operationId: Signup_to_create_a_legal_entity_v2_signup_post
      parameters:
      - name: authorization
        in: header
        required: false
        schema:
          type: string
          title: Authorization
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlatformSignupRequest'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlatformSignupResponse'
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlatformHttpException'
          description: Forbidden
        '409':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlatformHttpException'
          description: Conflict
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlatformSignupRequestValidationException'
          description: Unprocessable Entity
      tags:
      - Signup
  /v2/signup/session:
    post:
      summary: Create A Hosted Signup Session
      operationId: Create_a_Hosted_Signup_Session_v2_signup_session_post
      parameters:
      - name: authorization
        in: header
        required: false
        schema:
          type: string
          title: Authorization
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HostedSignupRequest'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HostedSignupResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      tags:
      - Signup
components:
  schemas:
    TaxClassEnum:
      type: string
      enum:
      - unset
      - corp
      - s_corp
      - partnership
      - disregarded
      - tax_exempt
      title: TaxClassEnum
      description: 'The IRS tax classification for an entity.


        In some circumstances, a company can elect to be treated different

        from the entity type for tax purposes. For example, an LLC can

        elect to be taxed as a corporation.

        - Corp: taxed as a corporation, the default for C Corps

        - S Corp: election using IRS Form 2553

        - Partnership: taxed as a partnership, the default for LPs

        - Disregarded: taxes pass through to the members, default for LLCs

        - Tax Exempt: an entity that is recognized by the IRS as being exempt from paying federal income taxes on its earnings'
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    AccountingYearEndMonth:
      type: string
      enum:
      - January
      - February
      - March
      - April
      - May
      - June
      - July
      - August
      - September
      - October
      - November
      - December
      title: AccountingYearEndMonth
    HostedSignupRequestBusinessInformation:
      properties:
        incorporation_region:
          anyOf:
          - $ref: '#/components/schemas/StateCode'
          - type: 'null'
        entity_type:
          anyOf:
          - $ref: '#/components/schemas/EntityTypeEnum_2'
          - type: 'null'
        tax_classification:
          anyOf:
          - $ref: '#/components/schemas/TaxClassEnum'
          - type: 'null'
        llc_managed_type:
          anyOf:
          - $ref: '#/components/schemas/LLCManagedTypeEnum'
          - type: 'null'
        business_name:
          anyOf:
          - type: string
          - type: 'null'
          title: Business Name
        business_purpose:
          anyOf:
          - type: string
          - type: 'null'
          title: Business Purpose
        ein:
          anyOf:
          - type: string
          - type: 'null'
          title: Ein
        incorporation_date:
          anyOf:
          - type: string
            format: date
          - type: 'null'
          title: Incorporation Date
        naics_code:
          anyOf:
          - type: string
          - type: 'null'
          title: Naics Code
        accounting_method:
          anyOf:
          - $ref: '#/components/schemas/AccountingMethod'
          - type: 'null'
        accounting_period:
          anyOf:
          - $ref: '#/components/schemas/AccountingPeriod'
          - type: 'null'
        accounting_year_end:
          anyOf:
          - $ref: '#/components/schemas/AccountingYearEndMonthNumber'
          - type: 'null'
        futa_liability_year:
          anyOf:
          - type: string
          - type: 'null'
          title: Futa Liability Year
      type: object
      title: HostedSignupRequestBusinessInformation
    Address:
      properties:
        id:
          anyOf:
          - type: string
          - type: 'null'
          title: Id
        address_line_1:
          type: string
          title: Address Line 1
        address_line_2:
          anyOf:
          - type: string
          - type: 'null'
          title: Address Line 2
        city:
          type: string
          title: City
        state:
          type: string
          title: State
        country:
          type: string
          title: Country
        postal_code:
          type: string
          title: Postal Code
      type: object
      required:
      - address_line_1
      - city
      - state
      - country
      - postal_code
      title: Address
    AccountingYearEndMonthNumber:
      type: integer
      enum:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      title: AccountingYearEndMonthNumber
    HostedSignupResponse:
      properties:
        url:
          type: string
          title: Url
          description: This is a session scoped URL which allows users to completed the signup process.
        created_at:
          type: string
          title: Created At
        expires_at:
          type: string
          title: Expires At
        legal_entity_id:
          type: string
          title: Legal Entity Id
      type: object
      required:
      - url
      - created_at
      - expires_at
      - legal_entity_id
      title: HostedSignupResponse
    LLCManagedTypeEnum:
      type: string
      enum:
      - member_managed
      - manager_managed
      title: LLCManagedTypeEnum
    PlatformSignupRequestValidationException:
      properties:
        message:
          type: string
          title: Message
        detail:
          anyOf:
          - type: string
          - items:
              additionalProperties: true
              type: object
            type: array
          title: Detail
        body:
          anyOf:
          - additionalProperties: true
            type: object
          - type: 'null'
          title: Body
      type: object
      required:
      - message
      - detail
      - body
      title: PlatformSignupRequestValidationException
    AccountingMethod:
      type: string
      enum:
      - accrual
      - cash
      title: AccountingMethod
    HostedSignupRequest:
      properties:
        business_name:
          type: string
          title: Business Name
        user_email:
          type: string
          title: User Email
        callback_url:
          type: string
          title: Callback Url
        legal_entity_id:
          anyOf:
          - type: string
          - type: 'null'
          title: Legal Entity Id
        business_information:
          anyOf:
          - $ref: '#/components/schemas/HostedSignupRequestBusinessInformation'
          - type: 'null'
        external_company_id:
          anyOf:
          - type: string
          - type: 'null'
          title: External Company Id
      type: object
      required:
      - business_name
      - user_email
      - callback_url
      title: HostedSignupRequest
    PlatformSignupResponse:
      properties:
        legal_entity_id:
          type: string
          title: Legal Entity Id
        url:
          anyOf:
          - type: string
          - type: 'null'
          title: Url
          description: This is the next URL to follow to complete the signup process.
      type: object
      required:
      - legal_entity_id
      title: PlatformSignupResponse
    app__platform__public__HostedSignupRequestBusinessInformation:
      properties:
        incorporation_region:
          anyOf:
          - $ref: '#/components/schemas/StateCode'
          - type: 'null'
        entity_type:
          anyOf:
          - $ref: '#/components/schemas/EntityTypeEnum'
          - type: 'null'
        tax_classification:
          anyOf:
          - $ref: '#/components/schemas/TaxClassEnum'
          - type: 'null'
        llc_managed_type:
          anyOf:
          - $ref: '#/components/schemas/LLCManagedTypeEnum'
          - type: 'null'
        business_name:
          anyOf:
          - type: string
          - type: 'null'
          title: Business Name
        business_purpose:
          anyOf:
          - type: string
          - type: 'null'
          title: Business Purpose
        ein:
          anyOf:
          - type: string
          - type: 'null'
          title: Ein
        incorporation_date:
          anyOf:
          - type: string
            format: date
          - type: 'null'
          title: Incorporation Date
        naics_code:
          anyOf:
          - type: string
          - type: 'null'
          title: Naics Code
        accounting_method:
          anyOf:
          - $ref: '#/components/schemas/AccountingMethod'
          - type: 'null'
        accounting_period:
          anyOf:
          - $ref: '#/components/schemas/AccountingPeriod'
          - type: 'null'
        accounting_year_end:
          anyOf:
          - $ref: '#/components/schemas/AccountingYearEndMonthNumber'
          - type: 'null'
        futa_liability_year:
          anyOf:
          - type: string
          - type: 'null'
          title: Futa Liability Year
      type: object
      title: HostedSignupRequestBusinessInformation
    app__platform__public__HostedSignupRequest:
      properties:
        business_name:
          type: string
          title: Business Name
        user_email:
          type: string
          title: User Email
        callback_url:
          type: string
          title: Callback Url
        legal_entity_id:
          anyOf:
          - type: string
          - type: 'null'
          title: Legal Entity Id
        business_information:
          anyOf:
          - $ref: '#/components/schemas/app__platform__public__HostedSignupRequestBusinessInformation'
          - type: 'null'
        external_company_id:
          anyOf:
          - type: string
          - type: 'null'
          title: External Company Id
      type: object
      required:
      - business_name
      - user_email
      - callback_url
      title: HostedSignupRequest
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    EntityTypeEnum:
      type: string
      enum:
      - unset
      - c_corp
      - p_corp
      - llc
      - llp
      - lp
      - gp
      title: EntityTypeEnum
    EntityTypeEnum_2:
      type: string
      enum:
      - unset
      - c_corp
      - p_corp
      - pllc
      - llc
      - llp
      - lp
      - gp
      title: EntityTypeEnum
    StateCode:
      type: string
      enum:
      - AL
      - AK
      - AZ
      - AR
      - CA
      - CO
      - CT
      - DE
      - DC
      - FL
      - GA
      - HI
      - ID
      - IL
      - IN
      - IA
      - KS
      - KY
      - LA
      - ME
      - MD
      - MA
      - MI
      - MN
      - MS
      - MO
      - MT
      - NE
      - NV
      - NH
      - NJ
      - NM
      - NY
      - NC
      - ND
      - OH
      - OK
      - OR
      - PA
      - RI
      - SC
      - SD
      - TN
      - TX
      - UT
      - VT
      - VA
      - WA
      - WV
      - WI
      - WY
      title: StateCode
    AccountingPeriod:
      type: string
      enum:
      - fiscal
      - calendar
      title: AccountingPeriod
    PlatformSignupRequest:
      properties:
        user_email:
          type: string
          title: User Email
        business_name:
          type: string
          title: Business Name
        entity_type:
          $ref: '#/components/schemas/EntityTypeEnum_2'
        tax_class:
          $ref: '#/components/schemas/TaxClassEnum'
        incorporation_region:
          $ref: '#/components/schemas/StateCode'
        incorporated_date:
          type: string
          format: date
          title: Incorporated Date
        ein:
          anyOf:
          - type: string
          - type: 'null'
          title: Ein
        llc_managed_type:
          anyOf:
          - $ref: '#/components/schemas/LLCManagedTypeEnum'
          - type: 'null'
        business_purpose:
          anyOf:
          - type: string
          - type: 'null'
          title: Business Purpose
        business_phone:
          anyOf:
          - type: string
          - type: 'null'
          title: Business Phone
        business_email:
          anyOf:
          - type: string
          - type: 'null'
          title: Business Email
        business_address:
          anyOf:
          - $ref: '#/components/schemas/Address'
          - type: 'null'
        mailing_address:
          anyOf:
          - $ref: '#/components/schemas/Address'
          - type: 'null'
        naics_code:
          anyOf:
          - type: string
          - type: 'null'
          title: Naics Code
        accounting_method:
          anyOf:
          - $ref: '#/components/schemas/AccountingMethod'
          - type: 'null'
        accounting_period:
          anyOf:
          - $ref: '#/components/schemas/AccountingPeriod'
          - type: 'null'
        accounting_year_end:
          anyOf:
          - $ref: '#/components/schemas/AccountingYearEndMonth'
          - type: 'null'
        futa_liability_year:
          anyOf:
          - type: string
          - type: 'null'
          title: Futa Liability Year
        external_company_id:
          anyOf:
          - type: string
          - type: 'null'
          title: External Company Id
        authorization_callback_url:
          anyOf:
          - type: string
          - type: 'null'
          title: Authorization Callback Url
      type: object
      required:
      - user_email
      - business_name
      - entity_type
      - tax_class
      - incorporation_region
      - incorporated_date
      title: PlatformSignupRequest
    PlatformHttpException:
      properties:
        message:
          type: string
          title: Message
        detail:
          type: string
          title: Detail
      type: object
      required:
      - message
      - detail
      title: PlatformHttpException
    app__platform__public__HostedSignupResponse:
      properties:
        url:
          type: string
          title: Url
          description: This is a session scoped URL which allows users to completed the signup process.
        created_at:
          type: string
          title: Created At
        expires_at:
          type: string
          title: Expires At
        legal_entity_id:
          type: string
          title: Legal Entity Id
      type: object
      required:
      - url
      - created_at
      - expires_at
      - legal_entity_id
      title: HostedSignupResponse
  securitySchemes:
    OAuth2PasswordBearer:
      type: oauth2
      flows:
        password:
          scopes: {}
          tokenUrl: /api/token
